image:
  file: .gitpod.dockerfile
tasks:
  - init: >
      . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh &&
      /home/gitpod/.pg_ctl/bin/pg_start > /dev/null &&
      sudo apt-get update &&
      sudo apt-get install -y wget gnupg2 &&
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - &&
      sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&
      sudo apt-get update &&
      sudo apt-get install -y google-chrome-stable &&
      wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip &&
      unzip chromedriver_linux64.zip &&
      sudo mv chromedriver /usr/bin/chromedriver &&
      sudo chown root:root /usr/bin/chromedriver &&
      sudo chmod +x /usr/bin/chromedriver &&
      rm chromedriver_linux64.zip
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
